services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - LS_LOG=trace-internal
    volumes:
      - './localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'
    labels:
      'org.springframework.boot.readiness-check.tcp.disable': true