spring:
  r2dbc:
    url: r2dbc:h2:file:///./data/testdb
    username: sa
    password: password
  flyway:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
    locations: classpath:db/migration
#logging:
#  level:
#    org.flywaydb: debug
#    org.h2: debug
