#!/bin/bash

awslocal dynamodb create-table \
             --table-name sectors_stores \
             --attribute-definitions \
                 AttributeName=sector,AttributeType=S \
                 AttributeName=date_from,AttributeType=S \
             --key-schema \
                 AttributeName=sector,KeyType=HASH \
                 AttributeName=date_from,KeyType=RANGE \
             --billing-mode=PAY_PER_REQUEST

awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"SW1A0"}, "date_from":{"S":"2024-01-01"}, "stores": {"L": [{"M":{"id": {"S": "abcdefghijk"}, "primary": {"BOOL": false}}},{"M":{"id": {"S": "marymary"}, "primary": {"BOOL": true}}}]}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"SW1A0"}, "date_from":{"S":"2024-09-30"}, "stores": {"L": [{"M":{"id": {"S": "september1"}, "primary": {"BOOL": false}}},{"M":{"id": {"S": "marymary"}, "primary": {"BOOL": true}}}]}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"SW1A0"}, "date_from":{"S":"2024-11-11"}, "stores": {"L": [{"M":{"id": {"S": "november1"}, "primary": {"BOOL": false}}},{"M":{"id": {"S": "marymary"}, "primary": {"BOOL": true}}}]}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"M43"}, "date_from":{"S":"2024-01-01"}, "stores": {"L": [{"M":{"id": {"S": "1234567890"}, "primary": {"BOOL": true}}},{"M":{"id": {"S": "0987654321"}, "primary": {"BOOL": false}}}]}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB10"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB11"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB12"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB13"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB14"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB15"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB16"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB17"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB18"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB19"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB20"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB21"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB22"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB23"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB24"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB25"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB26"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB27"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB28"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB29"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB31"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB32"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB33"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB34"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB35"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB36"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB37"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB38"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB39"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB40"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB41"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB42"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB43"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB44"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB45"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB46"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB47"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB48"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB49"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB50"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB51"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB52"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB53"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB54"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB55"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB56"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB57"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB58"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB59"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB91"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB92"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB95"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB96"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB97"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB98"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB101"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB106"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB107"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB113"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB115"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB116"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB117"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB118"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB119"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB123"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB124"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB125"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB129"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB130"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB140"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB154"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB155"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB156"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB157"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB158"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB159"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB165"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB166"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB167"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB169"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB210"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB211"}, "date_from":{"S":"2024-01-01"}}'
awslocal dynamodb put-item --table-name sectors_stores --item '{"sector":{"S":"AB217"}, "date_from":{"S":"2024-01-01"}}'

